### ISSUE TITLE
Installation failed using Drush or browser setup

### ISSUE THREAD

**Issue by johnreytanquinco** [goalgorilla/open_social#389]
I am using [Docker4Drupal](https://github.com/wodby/docker4drupal) to mount OpenSocial codebase but I was not able to successfully install it.

After I clone this repo, do `composer install` command then run docker-compose in the Drupal root folder, I got this error from the terminal, likely the same message I am receiving when I follow the regular browser installation setup:

```
/var/www/html # drush -v -y site-install social --db-url=mysql://drupal:drupal@mariadb/drupal --site-name=OpenSocial
Executing: mysql --defaults-extra-file=/tmp/drush_jfkhna --database=drupal --host=mariadb --silent  < /tmp/drush_HCFiEC > /dev/null
You are about to create a /var/www/html/sites/default/settings.php file and DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory /var/www/html/sites/default already exists - proceeding.                                                                                                    [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_jKOFnp --database=drupal --host=mariadb --silent  < /tmp/drush_IikdBH > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_CBpDin --database=drupal --host=mariadb --silent  < /tmp/drush_MjBPIb
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                    [ok]
Drupal\Component\Serialization\Exception\InvalidDataTypeException: yaml_parse(): end of stream reached without finding document 0 in                                         [error]
/var/www/html/core/lib/Drupal/Component/Serialization/YamlPecl.php:63
Stack trace:
#0 [internal function]: Drupal\Component\Serialization\YamlPecl::errorHandler(2, 'yaml_parse(): e...', '/var/www/html/c...', 45, Array)
#1 /var/www/html/core/lib/Drupal/Component/Serialization/YamlPecl.php(45): yaml_parse('#services:\n#  g...', 0, 0, Array)
#2 /var/www/html/core/lib/Drupal/Component/Serialization/Yaml.php(35): Drupal\Component\Serialization\YamlPecl::decode('#services:\n#  g...')
#3 /var/www/html/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php(343): Drupal\Component\Serialization\Yaml::decode('#services:\n#  g...')
#4 /var/www/html/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php(63): Drupal\Core\DependencyInjection\YamlFileLoader->loadFile('modules/group/m...')
#5 /var/www/html/core/lib/Drupal/Core/DrupalKernel.php(1254): Drupal\Core\DependencyInjection\YamlFileLoader->load('modules/group/m...')
#6 /var/www/html/core/lib/Drupal/Core/DrupalKernel.php(873): Drupal\Core\DrupalKernel->compileContainer()
#7 /var/www/html/core/lib/Drupal/Core/Installer/InstallerKernel.php(18): Drupal\Core\DrupalKernel->initializeContainer()
#8 /var/www/html/core/lib/Drupal/Core/DrupalKernel.php(797): Drupal\Core\Installer\InstallerKernel->initializeContainer()
#9 /var/www/html/core/lib/Drupal/Core/Extension/ModuleInstaller.php(540): Drupal\Core\DrupalKernel->updateModules(Array, Array)
#10 /var/www/html/core/lib/Drupal/Core/Extension/ModuleInstaller.php(191): Drupal\Core\Extension\ModuleInstaller->updateKernel(Array)
#11 /var/www/html/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#12 /var/www/html/social.profile(390): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, true)
#13 /var/www/html/core/includes/batch.inc(252): _social_install_module_batch(Array, 'grolesync', Array)
#14 /var/www/html/core/includes/form.inc(874): _batch_process()
#15 /var/www/html/core/includes/install.core.inc(619): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#16 /var/www/html/core/includes/install.core.inc(540): install_run_task(Array, Array)
#17 /var/www/html/core/includes/install.core.inc(117): install_run_tasks(Array)
#18 /home/www-data/.composer/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#19 /home/www-data/.composer/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#20 /home/www-data/.composer/vendor/drush/drush/commands/core/drupal/site_install.inc(84): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#21 /home/www-data/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(254): drush_core_site_install_version('social', Array)
#22 /home/www-data/.composer/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('social')
#23 /home/www-data/.composer/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#24 /home/www-data/.composer/vendor/drush/drush/includes/command.inc(199): drush_command('social')
#25 /home/www-data/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#26 /home/www-data/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#27 /home/www-data/.composer/vendor/drush/drush/drush.php(12): drush_main()
#28 {main}
Command dispatch complete                                                                                                                                                   [notice]
```

I noticed that the site is just broken because it actually installs some of the dependencies/modules. I can access the user URL and was able to log in as administrator.

But when I access its database from the container, it only created 44 tables, which is incomplete.

I actually posted an issue n [docker4drupal](https://github.com/wodby/docker4drupal/issues/151#issuecomment-305229693) repo that leads me to open one here.

Thanks!

**Comment by jaapjan** [comment]
More info here: 
https://www.drupal.org/node/2881371 and https://www.drupal.org/node/2882738
